//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Archive.java
//  @ Date : 10/27/2017
//  @ Author : 
//
//


import java.util.ArrayList;

public class Archive {
    private ArrayList<Record> records = new ArrayList<Record>();

    public Archive(){
        load();
    }

    public ArrayList<Record> getRecords() {
        return records;
    }

    public void setRecords(ArrayList<Record> records) {
        this.records = records;
    }

    private void load() {

    }

    public void utilizeGuest(Room room) {
        Record record = new Record(room);
        records.add(record);
    }
}
