//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hotel.java
//  @ Date : 10/27/2017
//  @ Author : 
//
//




public class Hotel {
	private String address;
	private String name;
	private RoomDescriptionCatalog roomDescriptionCatalog;
	private RoomList roomList;
	private ReservationCatalog reservationCatalog;
	private Archive archive;
	private GuestList guestList;
	private Controller controller;


	public Hotel(String name, String address) {
		this.name = name;
		this.address = address;
		roomDescriptionCatalog = new RoomDescriptionCatalog();
		roomList = new RoomList();
		reservationCatalog = new ReservationCatalog();
		guestList = new GuestList();
		archive = new Archive();
		controller = new Controller(guestList, roomDescriptionCatalog, reservationCatalog, roomList, archive);
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public RoomDescriptionCatalog getRoomDescriptionCatalog() {
		return roomDescriptionCatalog;
	}

	public void setRoomDescriptionCatalog(RoomDescriptionCatalog roomDescriptionCatalog) {
		this.roomDescriptionCatalog = roomDescriptionCatalog;
	}

	public RoomList getRoomList() {
		return roomList;
	}

	public void setRoomList(RoomList roomList) {
		this.roomList = roomList;
	}

	public ReservationCatalog getReservationCatalog() {
		return reservationCatalog;
	}

	public void setReservationCatalog(ReservationCatalog reservationCatalog) {
		this.reservationCatalog = reservationCatalog;
	}

	public Archive getArchive() {
		return archive;
	}

	public void setArchive(Archive archive) {
		this.archive = archive;
	}

	public GuestList getGuestList() {
		return guestList;
	}

	public void setGuestList(GuestList guestList) {
		this.guestList = guestList;
	}

	public Controller getController() {
		return controller;
	}

	public void setController(Controller controller) {
		this.controller = controller;
	}
}
