//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Record.java
//  @ Date : 10/27/2017
//  @ Author : 
//
//




public class Record {
	private String personalData;
	private int roomNumber;
	private String timeInterval;

	public String getPersonalData() {
		return personalData;
	}

	public void setPersonalData(String personalData) {
		this.personalData = personalData;
	}

	public int getRoomNumber() {
		return roomNumber;
	}

	public void setRoomNumber(int roomNumber) {
		this.roomNumber = roomNumber;
	}

	public String getTimeInterval() {
		return timeInterval;
	}

	public void setTimeInterval(String timeInterval) {
		this.timeInterval = timeInterval;
	}

	public Record(Room room) {
		roomNumber = room.getNumber();
		Guest guest = room.getGuest();
		personalData = guest.getPersonalData();
		String guestCheckInTime = guest.getCheckInTime();
		String guestCheckOutTime = guest.getCheckOutTime();
		String timeInterval = guestCheckInTime + "-" + guestCheckOutTime;
		this.timeInterval = timeInterval;
	}
}
