//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RoomDescription.java
//  @ Date : 10/27/2017
//  @ Author : 
//
//




public class RoomDescription {
	private int numberOfRelatedRooms;
	private String roomType;

	public boolean checkNumber(int number) {
		return number < numberOfRelatedRooms;
	}

	public int getNumberOfRelatedRooms() {
		return numberOfRelatedRooms;
	}

	public void setNumberOfRelatedRooms(int numberOfRelatedRooms) {
		this.numberOfRelatedRooms = numberOfRelatedRooms;
	}

	public String getRoomType() {
		return roomType;
	}

	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}

}
