//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RoomDescriptionCatalog.java
//  @ Date : 10/27/2017
//  @ Author : 
//
//


import java.util.HashMap;

public class RoomDescriptionCatalog {
	private HashMap<String, RoomDescription> roomDescriptions = new HashMap<>();

	public RoomDescription getRoomDescription(String roomType) {
		return roomDescriptions.get(roomType);
	}

	private void load() {

	}

	public HashMap<String, RoomDescription> getRoomDescriptions() {
		return roomDescriptions;
	}

	public void setRoomDescriptions(HashMap<String, RoomDescription> roomDescriptions) {
		this.roomDescriptions = roomDescriptions;
	}


}
